export const languages = [
  {title: "Tiếng Việt"},
  { title: "English (UK)" },
  { title: "中文(台灣)" },
  { title: "한국어" },
  { title: "日本語" },
  { title: "Français (France)" },
  { title: "ภาษาไทย" },
  { title: "Español" },
  { title: "Português (Brasil)" },
  { title: "Deutsch" },
  { title: "Italiano" },
];

export const titles = [
  {title: "Đăng ký"},
  { title: "Đăng nhập" },
  { title: "Messenger" },
  { title: "Facebook Lite"},
  { title: "Video" },
  { title: "Địa điểm" },
  { title: "Trò chơi" },
  { title: "Marketplace" },
  { title: "Meta Pay" },
  { title: "c" },
  { title: "Meta Quest" },
  { title: "Instagram" },
  { title: "Threads" },
  { title: "Chiến dịch gây quỹ" },
  { title: "Dịch vụ" },
  { title: "Trung tâm thông tin bỏ phiếu" },
  { title: "Chính sách quyền riêng tư" },
  { title: "Trung tâm quyền riêng tư" },
  { title: "Nhóm" },
  { title: "Giới thiệu" },
  { title: "Tạo quảng cáo" },
  { title: "Tạo Trang" },
  { title: "Nhà phát triển" },
  { title: "Tuyển dụng" },
  { title: "Cookie" },
  { title: "Lựa chọn quảng cáo" },
  { title: "Điều khoản" },
  { title: "Trợ giúp" },
  { title: "Tải thông tin liên hệ lên & đối tượng không phải người dùng" },
];



